### PR TITLE
Use CKEditor

### PR DESCRIPTION
**Pull request by jebbdomingo**

### CODE REVIEW

**Comment by jebbdomingo** [comment]
Note: please use the branch of nooku-ckeditor https://github.com/nooku/nooku-ckeditor/tree/feature/6-phpconfigurable for testing

**Comment by jebbdomingo** [comment]
Hi @johanjanssens, as with comparing with an identifier, yes I understand your point, I just overlook look it during testing.

**Comment by jebbdomingo** [comment]
@johanjanssens noted on the short tags, I was informed to use full php tag but probably it's not for template/view, I will revert it.
Regards

**Comment by johanjanssens** [comment]
@jebbdomingo No problem on the short tags, the rule is simple, in templates always use short tags, everywhere else never use short tags.

**Comment by jebbdomingo** [comment]
Noted @johanjanssens, I reverted the templates to use short tags

**Pull request merged**
